### ISSUE TITLE
SUMMARY meets expectations

### ISSUE THREAD

**Issue by ghost** [alteredcourse/prj-rev-bwfs-dasmoto#3]
Good job. You have good indentation and syntax. Add alt attributes and comments. As a next step, consider adding <div> tags to your code. You can nest elements in that code. I think you're ready for it!

**Comment by alteredcourse** [comment]
Hello,

Thanks for your comments. I'm not sure what you mean by "adding tags" to my code. If you have the opportunity, could you please clarify?
